Awesome books navigation
NoelLincoln/awesome-books pull request #3
Opened 2023-08-18 22:35 UTC by NoelLincoln

Hello 👋

We have implemented the required features in our awesome books project :
- A Navigation bar.
- Three content sections : books list, add book form and contact info.
- Links work as expected

2023-08-18 23:06 UTC, mwanawabangona requested changes
Hi @NoelLincoln @MPDADDY ,

Good job so far!
![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
* ✅  No linter errors :heavy_check_mark:
* ✅  Repo looks professional :briefcase:
* ✅  Good quality commits


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-18 23:06 UTC, mwanawabangona commented on index.html
> +    </div>
- [ ] `Required`
- [ ] Amazing work so far! 👏 
- [ ] However, the `copyright` on the contact section isn't put correctly as the wireframe provided 😞 
- [ ] Please see the screenshots below and Kindly correct the error 🥂 

`Your template`
![image](https://github.com/NoelLincoln/awesome-books/assets/66230306/e57e4610-af6e-41d1-aee9-64041340d669)

`provided wireframe`
![image](https://github.com/NoelLincoln/awesome-books/assets/66230306/05fc907c-2e75-4102-8336-7ed84f5a8cf2)

2023-08-19 07:10 UTC, MPDADDY commented
Implemented requested changes requested by the previous reviewer.

2023-08-19 07:19 UTC, usorfaitheloho approved these changes
Hi @NoelLincoln  , 
# STATUS: APPROVED! 🥇 💯 

![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-19 08:02 UTC, merged